// Capture configuration:
#define kNUMBER_OF_CAMERAS 6
#define kCAPTURED_IMAGE_WIDTH 320
#define kCAPTURED_IMAGE_HEIGHT 240

// Area to merge:
#define kMERGING_AREA_WIDTH 55
#define kMERGING_AREA_HEIGHT 55

#define kMOVEMENT_LOW_PASS_FILTER_CONSTANT 435


#define kTHREE_CHANNELS 3
